version: '3'
services:
  funcAPI:
    build: ./func_api
    image: func_api
    container_name: funcAPI2
    restart: always
    ports: 
      - 1984:6000
    environment:
      DATA_API_ROOT: https://cosbi5.ee.ncku.edu.tw/usData/
      DATA_API_USER: searchfunc
      DATA_API_PASSWORD: scbdfunc*
      PYTHONUNBUFFERED: 1

  Web:
    build: ./stock_project
    image: us_web
    container_name: Web2
    restart: always
    ports:
      - 1985:8000
    environment:
      DATA_API_ROOT: https://cosbi5.ee.ncku.edu.tw/usData/
      DATA_API_USER: searchfunc
      DATA_API_PASSWORD: scbdfunc*
      FUNC_API_ROOT: http://140.116.214.156:1984/usFunc2/
      # FUNC_API_ROOT: https://cosbi5.ee.ncku.edu.tw/usFunc2/
      AUTH_PATH: https://cosbi5.ee.ncku.edu.tw/usAuth/
      ROOT_PATH: https://cosbi5.ee.ncku.edu.tw/
      PYTHONUNBUFFERED: 1



